name: CI-CD

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3
      
      - name: Instalar contenedor
        run: composer install
      
      - name: Test
        run: ./vendor/bin/phpunit
        
      - name: Code Sniffer
        run: ./vendor/bin/phpcs app
      
      - name: Mess Detector
        run: ./vendor/bin/grumphp run
