name: CI-CD

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3
      
      - name: Instalar contenedor
        run: src/composer install
      
      - name: Test, Mess Detector y Code Sniffer
        run: .src/vendor/bin/grumphp run
