name: CI-CD

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3
      
      - run: cd src
      
      - name: Instalar contenedor
        run: composer install
      
      - name: Correr PHP Code Sniffer
        run: .vendor/bin/phpcs --standard=PSR12 .

      - name: Correr PHP Mess Detector
        run: .vendor/bin/phpmd . text cleancode
