name: CI-CD

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3
      
      - name: Instalar contenedor
        run: composer install
        working-directory: src
      
      - name: Test, Mess Detector y Code Sniffer
        run: ./vendor/bin/grumphp run
        working-directory: src
